name: Main
on: workflow_dispatch
jobs:
  build:
    name: Build the outputs
    runs-on: ubuntu-latest
    container:
      image: thomasweise/docker-texlive-full:2.0
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Make
        run: make
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: resume.pdf
          path: out/resume.pdf
