name: Main
on: workflow_dispatch
jobs:
  build:
    name: Build the outputs
    runs-on: ubuntu-latest
    container:
      image: thomasweise/docker-texlive-full:2.0
      options: --workdir /doc
      volumes:
        - ${{ github.workspace }}:/doc
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Make
        run: make
