name: Main
on: workflow_dispatch
jobs:
  build:
    name: Build the outputs
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Build
        uses: docker://thomasweise/docker-texlive-full:2.0
        with:
          args: >-
            --workdir '/doc'
            --volume ${{ github.workspace }}:/doc
            make
